// FIFA World Cup country flags and configuration

const FIFA_COUNTRIES: Record<string, string> = {
  // Group A–H 2026 (32 teams)
  Argentina: "fi fi-ar",
  Australia: "fi fi-au",
  Belgium: "fi fi-be",
  Brazil: "fi fi-br",
  Cameroon: "fi fi-cm",
  Canada: "fi fi-ca",
  Chile: "fi fi-cl",
  Colombia: "fi fi-co",
  "Costa Rica": "fi fi-cr",
  Croatia: "fi fi-hr",
  Denmark: "fi fi-dk",
  Ecuador: "fi fi-ec",
  England: "fi fi-gb-eng",
  France: "fi fi-fr",
  Germany: "fi fi-de",
  Ghana: "fi fi-gh",
  Iran: "fi fi-ir",
  Italy: "fi fi-it",
  Japan: "fi fi-jp",
  "South Korea": "fi fi-kr",
  Mexico: "fi fi-mx",
  Morocco: "fi fi-ma",
  Netherlands: "fi fi-nl",
  Nigeria: "fi fi-ng",
  Poland: "fi fi-pl",
  Portugal: "fi fi-pt",
  Qatar: "fi fi-qa",
  "Saudi Arabia": "fi fi-sa",
  Senegal: "fi fi-sn",
  Serbia: "fi fi-rs",
  Spain: "fi fi-es",
  Switzerland: "fi fi-ch",
  Tunisia: "fi fi-tn",
  "United States": "fi fi-us",
  Uruguay: "fi fi-uy",
  Wales: "fi fi-gb-wls",
  Scotland: "fi fi-gb-sct",
  Ireland: "fi fi-ie",
  Turkey: "fi fi-tr",
  Greece: "fi fi-gr",
  Sweden: "fi fi-se",
  Norway: "fi fi-no",
  Austria: "fi fi-at",
  Ukraine: "fi fi-ua",
  Hungary: "fi fi-hu",
  Romania: "fi fi-ro",
  "Czech Republic": "fi fi-cz",
  Slovakia: "fi fi-sk",
  "New Zealand": "fi fi-nz",
  "South Africa": "fi fi-za",
  Egypt: "fi fi-eg",
  Algeria: "fi fi-dz",
  Ivory: "fi fi-ci",
  "Ivory Coast": "fi fi-ci",
  China: "fi fi-cn",
  Indonesia: "fi fi-id",
  Peru: "fi fi-pe",
  Paraguay: "fi fi-py",
  Bolivia: "fi fi-bo",
  Venezuela: "fi fi-ve",
  Honduras: "fi fi-hn",
  Panama: "fi fi-pa",
  Jamaica: "fi fi-jm",
  Haiti: "fi fi-ht",
  Guatemala: "fi fi-gt",
  Cuba: "fi fi-cu",
  Russia: "fi fi-ru",
  Israel: "fi fi-il",
  Iraq: "fi fi-iq",
  UAE: "fi fi-ae",
  Bahrain: "fi fi-bh",
  Jordan: "fi fi-jo",
  Kuwait: "fi fi-kw",
  Thailand: "fi fi-th",
  Vietnam: "fi fi-vn",
  Philippines: "fi fi-ph",
  India: "fi fi-in",
  "Bosnia and Herzegovina": "fi fi-ba",
  Bosnia: "fi fi-ba",
  Curacao: "fi fi-cw",
  "Cape Verde": "fi fi-cv",
  "DR Congo": "fi fi-cd",
  "Congo DR": "fi fi-cd",
  Uzbekistan: "fi fi-uz",
};

export const FIFA_COUNTRY_NAMES = Object.keys(FIFA_COUNTRIES).sort();

export const getFifaFlagClass = (teamName: string): string => {
  return FIFA_COUNTRIES[teamName] || "fi fi-xx";
};

export const FifaTeamFlag = ({ teamName, className = "" }: { teamName: string; className?: string }) => {
  const flagClass = getFifaFlagClass(teamName);
  return <span className={`${flagClass} ${className}`}></span>;
};

export const FIFA_ROUND_NAMES: Record<number, string> = {
  0: "Group Stage",
  1: "Round of 32",
  2: "Round of 16",
  3: "Quarter-Finals",
  4: "Semi-Finals",
  5: "Final",
  6: "Custom Round",
};
