[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
buildCommand = "echo 'Using backend Dockerfile'"

[deploy]
startCommand = "node start.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
