version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
